### ISSUE TITLE
You can get accessibility audit to 100%

### ISSUE THREAD

**Issue by missKatiaPunter** [adaapp/Test-assignment2-team6#37]
If you look carefully at your accessibility report it tells you that the color does not contrast enough. You can fix it using this issue. I am marking it as a bug.

You can also add some images may be to your site with and without alt text and see how that affects your accessibility.
You can also look at other accessibility auditing tools and accessibility features that will improve your user experience. I marked this issue as a bug because accessibility flaws are considered accessibility bugs.

**Comment by umaimahyusuf** [comment]
changed colours to make accessibility 100%
